"""Seed data for 12 negotiation scenarios."""

SCENARIOS = [
    {
        "slug": "salary-negotiation",
        "title": "Salary Negotiation",
        "category": "Career",
        "description": "You've been offered a Senior Product Manager role. The initial offer feels low. Negotiate a fair compensation package.",
        "difficulty": "Medium",
        "duration": 10,
        "default_mode": "chat",
        "max_participants": 1,
        "objective": "Increase base salary by at least 15% and secure a signing bonus.",
        "context": "You are a senior candidate with 8 years of experience. The company loves you but their initial offer is $120K. Market rate is $140K–$155K.",
        "success_conditions": ["Base salary ≥ $138K", "Signing bonus ≥ $8K"],
        "failure_conditions": ["Accepts offer below $128K", "Walks away without counter"],
        "skills": ["Argumentation", "BATNA", "Anchoring"],
        "participants": [{
            "name": "Sarah Kim", "role": "Hiring Manager",
            "description": "Empathetic but has a tight budget. Wants to close quickly.",
            "goals": "Hire you within $130K total comp.",
            "interests": "Team fit, quick close, retention.",
            "hidden_interests": "Has a $145K approved ceiling but is measured on savings.",
            "constraints": "Cannot exceed $145K base without VP approval.",
            "batna": "Second candidate exists but 20% weaker.",
            "reservation_point": 145000,
            "personality": "Warm, collaborative, but firm on budget.",
            "priorities": ["Budget", "Speed", "Team fit"],
        }],
    },
    {
        "slug": "promotion-negotiation",
        "title": "Promotion Negotiation",
        "category": "Career",
        "description": "You've been performing above your level for a year. Negotiate a promotion with your director.",
        "difficulty": "Medium", "duration": 12, "default_mode": "chat", "max_participants": 1,
        "objective": "Secure promotion to Director with 20% raise this quarter.",
        "context": "You lead a team of 6. Peers at Director level are earning 25% more.",
        "success_conditions": ["Promotion committed this quarter", "Raise ≥ 15%"],
        "failure_conditions": ["Vague timeline > 6 months", "No raise commitment"],
        "skills": ["Active Listening", "Argumentation", "Strategy"],
        "participants": [{
            "name": "Michael Chen", "role": "Director of Engineering",
            "description": "Data-driven, cautious about promotions.",
            "goals": "Retain you without over-committing.", "interests": "Team stability, performance data.",
            "hidden_interests": "Fears losing you to competitor.", "constraints": "Promotions require HR sign-off.",
            "batna": "Could counter with retention bonus.", "reservation_point": 0.18,
            "personality": "Analytical, guarded.", "priorities": ["Retention", "Fairness", "Team"],
        }],
    },
    {
        "slug": "enterprise-discount",
        "title": "Enterprise Discount Request",
        "category": "Sales",
        "description": "A major client demands a 30% discount on your SaaS enterprise deal. Protect margins.",
        "difficulty": "Hard", "duration": 15, "default_mode": "chat", "max_participants": 2,
        "objective": "Close deal with maximum 12% discount and multi-year commitment.",
        "context": "$1.2M annual deal. Prospect claims competitor offers 30% lower.",
        "success_conditions": ["Discount ≤ 15%", "Multi-year term ≥ 2 years"],
        "failure_conditions": ["Discount > 25%", "Deal collapses"],
        "skills": ["Questioning", "Anchoring", "Concessions"],
        "participants": [
            {"name": "Elena Rostova", "role": "VP Procurement",
             "description": "Aggressive, focused on savings.", "goals": "30% discount.",
             "interests": "Cost reduction, KPI bonus.", "hidden_interests": "Will accept 18% if terms extend to 3 years.",
             "constraints": "Reports to CFO on savings.", "batna": "Competitor bid.",
             "reservation_point": 0.18, "personality": "Hardball, direct.", "priorities": ["Price", "Terms"]},
            {"name": "Marcus Chen", "role": "Legal Counsel",
             "description": "Reviews contract terms carefully.", "goals": "Strong SLAs, exit clauses.",
             "interests": "Risk mitigation.", "hidden_interests": "Prefers 2-yr max terms.",
             "constraints": "Must approve any liability.", "batna": "Reject deal.",
             "reservation_point": 0, "personality": "Cautious, procedural.", "priorities": ["SLA", "Risk"]},
        ],
    },
    {
        "slug": "difficult-client",
        "title": "Difficult Client — Churn Risk",
        "category": "Sales",
        "description": "A key client threatens to cancel their contract after a service failure. Retain them.",
        "difficulty": "Hard", "duration": 12, "default_mode": "chat", "max_participants": 1,
        "objective": "Retain the client at ≥ 80% original ACV with commitment.",
        "context": "Client had a 4-hour outage last week. They're evaluating alternatives.",
        "success_conditions": ["Client renews", "ACV ≥ 80%"],
        "failure_conditions": ["Client cancels", "ACV < 60%"],
        "skills": ["Active Listening", "Empathy", "Conflict Management"],
        "participants": [{
            "name": "David Sterling", "role": "Client CTO",
            "description": "Frustrated, feels ignored.", "goals": "Compensation + guarantees.",
            "interests": "Reliability, respect.", "hidden_interests": "Wants to stay but needs face-saving win.",
            "constraints": "Board is watching.", "batna": "Competitor demo scheduled.",
            "reservation_point": 0.7, "personality": "Emotional, direct.", "priorities": ["Trust", "Uptime"],
        }],
    },
    {
        "slug": "vendor-price-increase",
        "title": "Vendor Price Increase",
        "category": "Procurement",
        "description": "Your key supplier wants to raise prices by 12%. Limit the increase.",
        "difficulty": "Medium", "duration": 10, "default_mode": "chat", "max_participants": 1,
        "objective": "Limit price increase to 7% max.",
        "context": "3-year relationship. Alternative vendors exist but switching costs are high.",
        "success_conditions": ["Increase ≤ 7%", "Extended terms"],
        "failure_conditions": ["Accepts ≥ 10%", "Relationship damaged"],
        "skills": ["Questioning", "BATNA", "Concessions"],
        "participants": [{
            "name": "Alexander Vance", "role": "Vendor Account Director",
            "description": "Firm but relationship-oriented.", "goals": "Full 12% raise.",
            "interests": "Margin, retention.", "hidden_interests": "Accepts 6-8% for 3-yr renewal.",
            "constraints": "Corporate mandate on raises.", "batna": "Switch to your competitor.",
            "reservation_point": 0.06, "personality": "Professional, patient.", "priorities": ["Margin", "Loyalty"],
        }],
    },
    {
        "slug": "contract-renewal",
        "title": "Contract Renewal",
        "category": "Procurement",
        "description": "Renegotiate a critical software contract on better terms.",
        "difficulty": "Medium", "duration": 12, "default_mode": "chat", "max_participants": 1,
        "objective": "Improve terms: 10% discount, better SLA, quarterly billing.",
        "context": "Current 12-month contract expires in 30 days.",
        "success_conditions": ["Discount ≥ 8%", "SLA improved"],
        "failure_conditions": ["No discount", "Locked into 3-year"],
        "skills": ["Strategy", "Concessions", "BATNA"],
        "participants": [{
            "name": "Sarah Kim", "role": "Account Executive",
            "description": "Quota-driven, negotiates hard on term length.", "goals": "Multi-year lock-in.",
            "interests": "TCV, retention bonus.", "hidden_interests": "Approved to give 12% off for 2-yr.",
            "constraints": "Cannot discount base tier below floor.", "batna": "Let contract auto-renew.",
            "reservation_point": 0.12, "personality": "Charming, persistent.", "priorities": ["TCV", "Term"],
        }],
    },
    {
        "slug": "team-resource-conflict",
        "title": "Team Resource Conflict",
        "category": "Management",
        "description": "Two teams want the same engineer for their Q4 project. Mediate.",
        "difficulty": "Medium", "duration": 10, "default_mode": "chat", "max_participants": 2,
        "objective": "Resolve without damaging either team's roadmap.",
        "context": "You lead engineering. Two directors both need Priya, your best backend engineer.",
        "success_conditions": ["Both teams accept plan", "No escalation"],
        "failure_conditions": ["One team escalates to VP", "Engineer quits due to conflict"],
        "skills": ["Conflict Management", "Active Listening", "Strategy"],
        "participants": [
            {"name": "Michael Chen", "role": "Director, Platform",
             "description": "Believes his project is P0.", "goals": "Full-time Priya for 3 months.",
             "interests": "Q4 launch success.", "hidden_interests": "Can accept 50% allocation.",
             "constraints": "Committed to CEO.", "batna": "Escalate to VP.",
             "reservation_point": 0.5, "personality": "Aggressive, political.", "priorities": ["Launch", "Ownership"]},
            {"name": "Elena Rostova", "role": "Director, Growth",
             "description": "Data-driven, quieter but firm.", "goals": "Priya 60% time.",
             "interests": "Growth experiments.", "hidden_interests": "Can find external contractor if needed.",
             "constraints": "Growth OKRs at risk.", "batna": "Hire contractor.",
             "reservation_point": 0.3, "personality": "Analytical.", "priorities": ["OKRs", "Quality"]},
        ],
    },
    {
        "slug": "project-deadline",
        "title": "Project Deadline Push-back",
        "category": "Management",
        "description": "Your team needs 3 more weeks. Convince the CEO to move the deadline.",
        "difficulty": "Hard", "duration": 10, "default_mode": "chat", "max_participants": 1,
        "objective": "Secure ≥ 2 weeks additional runway without losing credibility.",
        "context": "Launch is announced. CEO promised the board a fixed date.",
        "success_conditions": ["Deadline extended ≥ 14 days", "Trust maintained"],
        "failure_conditions": ["Deadline unchanged", "Loss of confidence"],
        "skills": ["Argumentation", "Strategy", "BATNA"],
        "participants": [{
            "name": "David Sterling", "role": "CEO",
            "description": "Public-facing, sensitive to optics.", "goals": "Hit the announced date.",
            "interests": "Board trust, market perception.", "hidden_interests": "Would prefer quality over speed if framed right.",
            "constraints": "Announced date is public.", "batna": "Force launch as-is.",
            "reservation_point": 14, "personality": "Impatient, high-standards.", "priorities": ["Reputation", "Speed"],
        }],
    },
    {
        "slug": "revenue-share",
        "title": "Revenue Share Deal",
        "category": "Partnership",
        "description": "Negotiate a revenue share with a distribution partner.",
        "difficulty": "Hard", "duration": 15, "default_mode": "chat", "max_participants": 2,
        "objective": "Keep partner share ≤ 30% with exclusivity carve-outs.",
        "context": "Distributor has strong channel access. They want 40% rev share.",
        "success_conditions": ["Share ≤ 32%", "No exclusivity on core markets"],
        "failure_conditions": ["Share ≥ 38%", "Full exclusivity granted"],
        "skills": ["Anchoring", "Concessions", "Strategy"],
        "participants": [
            {"name": "Alexander Vance", "role": "Partner CEO",
             "description": "Old-school dealmaker.", "goals": "40% share + exclusivity.",
             "interests": "Long-term revenue.", "hidden_interests": "Accepts 28-30% for 3-yr exclusive.",
             "constraints": "Board pushes for exclusivity.", "batna": "Sign with competitor.",
             "reservation_point": 0.28, "personality": "Charming, tough.", "priorities": ["Share", "Exclusivity"]},
            {"name": "Marcus Chen", "role": "Partner CFO",
             "description": "Numbers-focused.", "goals": "Maximize NPV.",
             "interests": "Financial modelling.", "hidden_interests": "Would trade % for volume commitment.",
             "constraints": "Must hit quarterly targets.", "batna": "Renegotiate later.",
             "reservation_point": 0.3, "personality": "Detail-obsessed.", "priorities": ["NPV", "Volume"]},
        ],
    },
    {
        "slug": "strategic-partnership",
        "title": "Strategic Partnership",
        "category": "Partnership",
        "description": "Frame a joint go-to-market partnership with a larger firm.",
        "difficulty": "Hard", "duration": 15, "default_mode": "chat", "max_participants": 1,
        "objective": "Secure co-marketing budget and joint pipeline commitment.",
        "context": "You are smaller but strategic. They control the customer channel.",
        "success_conditions": ["Marketing budget ≥ $200K", "Joint pipeline ≥ $2M"],
        "failure_conditions": ["No budget", "Junior sponsor only"],
        "skills": ["Strategy", "Active Listening", "Argumentation"],
        "participants": [{
            "name": "Elena Rostova", "role": "SVP Partnerships",
            "description": "Skeptical of smaller partners.", "goals": "Pilot program only.",
            "interests": "Low risk, high signal.", "hidden_interests": "Under pressure to show partner wins to CEO.",
            "constraints": "Requires executive sponsor approval.", "batna": "Work with 3 other partners.",
            "reservation_point": 100000, "personality": "Reserved, strategic.", "priorities": ["Risk", "Signal"],
        }],
    },
    {
        "slug": "internal-conflict",
        "title": "Internal Team Conflict",
        "category": "Conflict",
        "description": "Two senior engineers refuse to work together after a heated dispute. Resolve.",
        "difficulty": "Medium", "duration": 10, "default_mode": "chat", "max_participants": 2,
        "objective": "Restore working relationship without losing either engineer.",
        "context": "Both are top performers. Team velocity has dropped 40%.",
        "success_conditions": ["Both commit to work agreement", "No resignation"],
        "failure_conditions": ["One quits", "Deeper conflict"],
        "skills": ["Active Listening", "Empathy", "Conflict Management"],
        "participants": [
            {"name": "Michael Chen", "role": "Senior Engineer A",
             "description": "Feels disrespected.", "goals": "Recognition + apology.",
             "interests": "Respect, quality.", "hidden_interests": "Actually admires the other engineer.",
             "constraints": "Considering offers.", "batna": "Leave the company.",
             "reservation_point": 0, "personality": "Proud, emotional.", "priorities": ["Respect", "Quality"]},
            {"name": "Sarah Kim", "role": "Senior Engineer B",
             "description": "Feels micromanaged.", "goals": "Autonomy.",
             "interests": "Ownership, technical freedom.", "hidden_interests": "Ready to compromise for right project.",
             "constraints": "Loyal to the company.", "batna": "Ask for transfer.",
             "reservation_point": 0, "personality": "Blunt, principled.", "priorities": ["Autonomy", "Impact"]},
        ],
    },
    {
        "slug": "service-failure-crisis",
        "title": "Service Failure Crisis",
        "category": "Conflict",
        "description": "A high-profile customer had a data incident. Manage the crisis conversation.",
        "difficulty": "Hard", "duration": 12, "default_mode": "chat", "max_participants": 1,
        "objective": "Preserve the relationship and avoid legal escalation.",
        "context": "Customer's data was briefly exposed. Legal team is drafting notice.",
        "success_conditions": ["No lawsuit", "Contract preserved", "Communication plan agreed"],
        "failure_conditions": ["Public escalation", "Contract terminated"],
        "skills": ["Empathy", "Conflict Management", "Active Listening"],
        "participants": [{
            "name": "David Sterling", "role": "Customer General Counsel",
            "description": "Cool, professional, protective of client.", "goals": "Full disclosure + remediation.",
            "interests": "Risk mitigation, brand protection.", "hidden_interests": "Prefers quiet fix over public fight.",
            "constraints": "Board is briefed.", "batna": "File legal notice.",
            "reservation_point": 0, "personality": "Precise, unemotional.", "priorities": ["Disclosure", "Remedy"],
        }],
    },
]


# ---------- Participant gender (for TTS voice selection) ----------
GENDERS = {
    "Sarah Kim": "female",
    "Michael Chen": "male",
    "Elena Rostova": "female",
    "Marcus Chen": "male",
    "David Sterling": "male",
    "Alexander Vance": "male",
}

# ---------- Russian role translations (by English role) ----------
ROLE_RU = {
    "Hiring Manager": "Менеджер по найму",
    "Director of Engineering": "Директор по инженерии",
    "VP Procurement": "Вице-президент по закупкам",
    "Legal Counsel": "Юрисконсульт",
    "Client CTO": "CTO клиента",
    "Vendor Account Director": "Директор по работе с клиентами (поставщик)",
    "Account Executive": "Менеджер по работе с клиентами",
    "Director, Platform": "Директор, Платформа",
    "Director, Growth": "Директор, Рост",
    "CEO": "CEO",
    "Partner CEO": "CEO партнёра",
    "Partner CFO": "CFO партнёра",
    "SVP Partnerships": "Старший вице-президент по партнёрствам",
    "Senior Engineer A": "Старший инженер A",
    "Senior Engineer B": "Старший инженер B",
    "Customer General Counsel": "Главный юрист клиента",
}

# ---------- Russian scenario translations (user-visible fields) ----------
SCENARIO_RU = {
    "salary-negotiation": {
        "title": "Переговоры о зарплате",
        "description": "Вам предложили роль старшего продакт-менеджера. Первоначальное предложение кажется низким. Договоритесь о справедливом компенсационном пакете.",
        "objective": "Увеличить базовый оклад минимум на 15% и получить бонус при подписании.",
    },
    "promotion-negotiation": {
        "title": "Переговоры о повышении",
        "description": "Вы уже год работаете выше своего уровня. Договоритесь о повышении со своим директором.",
        "objective": "Добиться повышения до директора с ростом оклада на 20% в этом квартале.",
    },
    "enterprise-discount": {
        "title": "Запрос корпоративной скидки",
        "description": "Крупный клиент требует скидку 30% на корпоративную SaaS-сделку. Защитите маржу.",
        "objective": "Закрыть сделку со скидкой не более 12% и многолетним обязательством.",
    },
    "difficult-client": {
        "title": "Сложный клиент — риск оттока",
        "description": "Ключевой клиент угрожает расторгнуть контракт после сбоя в сервисе. Удержите его.",
        "objective": "Удержать клиента на уровне ≥80% исходной стоимости контракта с обязательством.",
    },
    "vendor-price-increase": {
        "title": "Повышение цены поставщиком",
        "description": "Ваш ключевой поставщик хочет поднять цены на 12%. Ограничьте повышение.",
        "objective": "Ограничить повышение цены максимум 7%.",
    },
    "contract-renewal": {
        "title": "Продление контракта",
        "description": "Пересмотрите критически важный контракт на ПО на более выгодных условиях.",
        "objective": "Улучшить условия: скидка 10%, лучший SLA, ежеквартальная оплата.",
    },
    "team-resource-conflict": {
        "title": "Конфликт ресурсов в команде",
        "description": "Две команды претендуют на одного инженера для проекта Q4. Выступите медиатором.",
        "objective": "Разрешить конфликт без ущерба для дорожных карт обеих команд.",
    },
    "project-deadline": {
        "title": "Перенос дедлайна проекта",
        "description": "Вашей команде нужно ещё 3 недели. Убедите CEO перенести срок.",
        "objective": "Получить минимум 2 недели дополнительного времени, не потеряв доверие.",
    },
    "revenue-share": {
        "title": "Сделка о разделе выручки",
        "description": "Договоритесь о разделе выручки с дистрибьютором.",
        "objective": "Удержать долю партнёра ≤30% с исключениями по эксклюзивности.",
    },
    "strategic-partnership": {
        "title": "Стратегическое партнёрство",
        "description": "Оформите совместное go-to-market партнёрство с более крупной компанией.",
        "objective": "Получить со-маркетинговый бюджет и обязательство по совместному пайплайну.",
    },
    "internal-conflict": {
        "title": "Внутренний конфликт в команде",
        "description": "Два старших инженера отказываются работать вместе после острого спора. Разрешите ситуацию.",
        "objective": "Восстановить рабочие отношения, не потеряв ни одного инженера.",
    },
    "service-failure-crisis": {
        "title": "Кризис из-за сбоя сервиса",
        "description": "У крупного клиента произошёл инцидент с данными. Проведите кризисный разговор.",
        "objective": "Сохранить отношения и избежать юридической эскалации.",
    },
}

